services:
  aws:
    build: ./config/aws/
    image: aws:latest
    volumes:
      - ./cloud:/app
    env_file:
      - .env
  go:
    build: ./config/golang/
    image: golang:latest
    volumes:
      - ./cloud/generator:/app
