version: "3.9"
services:
  web:
    build:
      context: "./.config/docker"
      dockerfile: web.Dockerfile
    volumes:
      - type: bind
        source: $PWD/backend
        target: /opt/app
    ports:
      - "4321:4321"
    container_name: nulllab
